export const EVENT_CATEGORIES = {
  request: 'EVENT_CATEGORIES.request',
  success: 'EVENT_CATEGORIES.success',
  fail: 'EVENT_CATEGORIES.fail',
};
export const EVENT_CATEGORIES_NAMES = {
  request: 'EVENT_CATEGORIES_NAMES.request',
  success: 'EVENT_CATEGORIES_NAMES.success',
  fail: 'EVENT_CATEGORIES_NAMES.fail',
};

export const CLEAR_EVENT_CATEGORIES_ERRORS = 'CLEAR_EVENT_CATEGORIES_ERRORS';
export const RESET_EVENT_CATEGORIES_STATE = 'RESET_EVENT_CATEGORIES_STATE';
