import { Columns2, Columns3, Columns4, RectangleHorizontal } from 'lucide-react';

export default [
  {
    label: 'Column',
    type: 'column',
    numOfColumns: 1,
    icon: RectangleHorizontal,
    json: {
      type: 'column',
      styleClassName: 'grid gap-0 grid-cols-1',
      styles: {},
      properties: {
        containerType: 'grid',
        columns: 1,
      },
      block: [
        {
          index: 0,
          blockStyleClassName: 'p-2 flex',
          blockStyles: {
            justifyContent: 'center',
            alignItems: 'center',
            gap: '2px',
            paddingTop: '2px',
            paddingBottom: '2px',
            paddingLeft: '2px',
            paddingRight: '2px',
          },
          subBlock: [],
        },
      ],
    },
  },
  {
    label: '2 Column',
    type: 'column',
    numOfColumns: 2,
    icon: Columns2,
    json: {
      type: 'column',
      styleClassName: 'grid gap-0 grid-cols-2',
      styles: {},
      properties: {
        containerType: 'grid',
        columns: 2,
      },
      block: [
        {
          index: 0,
          blockStyleClassName: 'p-2 flex',
          blockStyles: {
            justifyContent: 'center',
            alignItems: 'center',
            gap: '2px',
            paddingTop: '2px',
            paddingBottom: '2px',
            paddingLeft: '2px',
            paddingRight: '2px',
          },
          subBlock: [],
        },
        {
          index: 1,
          blockStyleClassName: 'p-2 flex',
          blockStyles: {
            justifyContent: 'center',
            alignItems: 'center',
            gap: '2px',
            paddingTop: '2px',
            paddingBottom: '2px',
            paddingLeft: '2px',
            paddingRight: '2px',
          },
          subBlock: [],
        },
      ],
    },
  },
  {
    label: '3 Column',
    type: 'column',
    numOfColumns: 3,
    icon: Columns3,
    json: {
      type: 'column',
      styleClassName: 'grid gap-0 grid-cols-3',
      styles: {},
      properties: {
        containerType: 'grid',
        columns: 3,
      },
      block: [
        {
          index: 0,
          blockStyleClassName: 'p-2 flex',
          blockStyles: {
            justifyContent: 'center',
            alignItems: 'center',
            gap: '2px',
            paddingTop: '2px',
            paddingBottom: '2px',
            paddingLeft: '2px',
            paddingRight: '2px',
          },
          subBlock: [],
        },
        {
          index: 1,
          blockStyleClassName: 'p-2 flex',
          blockStyles: {
            justifyContent: 'center',
            alignItems: 'center',
            gap: '2px',
            paddingTop: '2px',
            paddingBottom: '2px',
            paddingLeft: '2px',
            paddingRight: '2px',
          },
          subBlock: [],
        },
        {
          index: 2,
          blockStyleClassName: 'p-2 flex',
          blockStyles: {
            justifyContent: 'center',
            alignItems: 'center',
            gap: '2px',
            paddingTop: '2px',
            paddingBottom: '2px',
            paddingLeft: '2px',
            paddingRight: '2px',
          },
          subBlock: [],
        },
      ],
    },
  },
  {
    label: '4 Column',
    type: 'column',
    numOfColumns: 4,
    icon: Columns4,
    json: {
      type: 'column',
      styleClassName: 'grid gap-0 grid-cols-4',
      styles: {},
      properties: {
        containerType: 'grid',
        columns: 4,
      },
      block: [
        {
          index: 0,
          blockStyleClassName: 'p-2 flex',
          blockStyles: {
            justifyContent: 'center',
            alignItems: 'center',
            gap: '2px',
            paddingTop: '2px',
            paddingBottom: '2px',
            paddingLeft: '2px',
            paddingRight: '2px',
          },
          subBlock: [],
        },
        {
          index: 1,
          blockStyleClassName: 'p-2 flex',
          blockStyles: {
            justifyContent: 'center',
            alignItems: 'center',
            gap: '2px',
            paddingTop: '2px',
            paddingBottom: '2px',
            paddingLeft: '2px',
            paddingRight: '2px',
          },
          subBlock: [],
        },
        {
          index: 2,
          blockStyleClassName: 'p-2 flex',
          blockStyles: {
            justifyContent: 'center',
            alignItems: 'center',
            gap: '2px',
            paddingTop: '2px',
            paddingBottom: '2px',
            paddingLeft: '2px',
            paddingRight: '2px',
          },
          subBlock: [],
        },
        {
          index: 3,
          blockStyleClassName: 'p-2 flex',
          blockStyles: {
            justifyContent: 'center',
            alignItems: 'center',
            gap: '2px',
            paddingTop: '2px',
            paddingBottom: '2px',
            paddingLeft: '2px',
            paddingRight: '2px',
          },
          subBlock: [],
        },
      ],
    },
  },
];
