export const ADMINISTRATORS = {
  request: 'ADMINISTRATORS.request',
  success: 'ADMINISTRATORS.success',
  fail: 'ADMINISTRATORS.fail',
};

export const CLEAR_ADMINISTRATORS_ERRORS = 'CLEAR_ADMINISTRATORS_ERRORS';
export const RESET_ADMINISTRATORS_STATE = 'RESET_ADMINISTRATORS_STATE';
