export const SUPPER_ADMIN_MOSQUES = {
  request: 'SUPPER_ADMIN_MOSQUES_REQUEST',
  success: 'SUPPER_ADMIN_MOSQUES_SUCCESS',
  fail: 'SUPPER_ADMIN_MOSQUES_FAIL',
};

export const CLEAR_MOSQUE_ERRORS = 'CLEAR_MOSQUE_ERRORS';
export const RESET_MOSQUE_STATE = 'RESET_MOSQUE_STATE';
